# Generated by Django 5.1 on 2024-12-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='imagess')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False, help_text='0=default,1=Hidden')),
            ],
        ),
    ]
