# Generated by Django 5.1 on 2024-12-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='category_product',
            name='product_image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
