# Generated by Django 5.1 on 2024-12-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='category_product',
            name='product_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
